springdoc:
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  cache:
    disabled: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  use-fqn: true